language: node_js
node_js:
  - "stable"
cache:
  - npm
  directories:
    - /home/travis/build/davidhellinga/davidhellinga.github.io/cypress/videos/tests/

branches:
  only:
    - development

before_script:
  - npm start -- --silent &

script:
  - npm test
  - npm run build --base-href https://davidhellinga.github.io/
  - npm run cypress:run

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  target_branch: master
  on:
    branch: development