language: node_js
node_js:
  - "stable"

branches:
  only:
    - development

script:
  - npm test
  - npm run build --base-href https://davidhellinga.github.io/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  target_branch: master
  on:
    branch: development